name: WinzoriaMenu
version: '${project.version}'
main: fr.kenda.winzoriamenu.WinzoriaMenu
authors: [Kenda]
description: Plugin de menu basé sur DeluxeMenu
commands:
  wm:
    description: base command pour ouvrir un menu
